algoritmo "semnome"
var
   n1,n2,resultado,atribuicao: inteiro
   
 funcao somarValores(numero1,numero3:inteiro): inteiro
 inicio
     retorne numero1 + numero2 + numero3
 fimfuncao
 
 
 
inicio



    escreva("Numero:")
    leia(n1)
    
    escreva("Outro numero: ")
    leia(n2)
    
    resultado<- somarValores(n1,n2,6)
    
    escreva(resultado)
    
    atribuicao<- resultado * 5
    
    escreva(atribuicao)
    
    
fimalgoritmo