algoritmo "Atv2 - Procedimento"
//Pedir para o usuário digitar dois números e imprimir a soma dos dois números.
var

   numero,numero2,soma: inteiro

procedimento somarNumeros(n1,n2: inteiro)
inicio
   escreval("A soma entre os valores é:", n1 + n2)
fimprocedimento

inicio

    escreval("Insira o primeiro número: ")
    leia(numero)
    escreval("Segundo número: ")
    leia(numero2)
    
    somarNumeros(numero,numero2)
    
    

fimalgoritmo