algoritmo "semnome"
var
   nome,sexo,estadoCivil: caractere
   tempoCasada: inteiro
inicio
    escreva("Nome: ")
    leia(nome)
    
    escreva("Sexo: [M]Masculino [F] Feminino ")
    leia(sexo)
    
    escreva("Estado Civil: [C] Casado(a) [S] Solteiro  ")
    leia(estadoCivil)

    se(sexo = "F") e (estadoCivil.tamanho <  ) entao
      escreva("Casada a quantos anos: ")
      leia(tempoCasada)
      escreva("Esta casada a ",tempoCasada," anos")
    fimse



fimalgoritmo